### ISSUE TITLE
Error 7102 on attempt to use the .users_supervisor endpoint

### ISSUE THREAD

**Issue by radyakin** [radyakin/susoapi#8]
Trace:
```
. .suso.users_supervisor "`superid'"
  ---------------------------------------------------------------------------------------------- begin SuSo.users_supervisor ---
  - version 16
  - version 16.0
  - args guid
  - python: users_supervisor("`guid'")
  = python: users_supervisor("-----SOME GUID----")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in users_supervisor
KeyError: 'FullName'
  ------------------------------------------------------------------------------------------------ end SuSo.users_supervisor ---
r(7102);
```

**Comment by radyakin** [comment]
Issue occurred for supervisor accounts with **_any_** of the optional fields left empty:
- _FullName;_
- _Phone;_
- _Email;_
